package com.nexuscore.awakenedrealms;
import android.app.*;import android.os.*;import android.content.*;import android.text.InputType;import android.widget.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import org.json.*;import androidx.credentials.*;import androidx.credentials.exceptions.GetCredentialException;import com.google.android.libraries.identity.googleid.*;
public final class MainActivity extends Activity{
 private final Handler ui=new Handler(Looper.getMainLooper());private TextView status,metrics,tasks,events,tree;private SystemGraphView graph;private volatile boolean running;private String endpoint,token;private long connectedAt;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.status);metrics=findViewById(R.id.metrics);tasks=findViewById(R.id.tasks);events=findViewById(R.id.events);tree=findViewById(R.id.tree);graph=findViewById(R.id.graph);SharedPreferences p=getSharedPreferences("nexus",MODE_PRIVATE);endpoint=p.getString("endpoint","https://control.nexuscore.example");token=p.getString("token","");findViewById(R.id.signin).setOnClickListener(v->googleSignIn());findViewById(R.id.configure).setOnClickListener(v->configure());findViewById(R.id.pause).setOnClickListener(v->control("pause-autonomy"));findViewById(R.id.resume).setOnClickListener(v->control("resume-autonomy"));findViewById(R.id.preflight).setOnClickListener(v->control("run-preflight"));}
 @Override protected void onStart(){super.onStart();running=true;connectedAt=System.currentTimeMillis();snapshot();stream();tick();}@Override protected void onStop(){running=false;super.onStop();}
 private HttpURLConnection open(String path)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(endpoint+path).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(35000);c.setRequestProperty("Accept","application/json");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);return c;}
 private String read(HttpURLConnection c)throws Exception{BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder b=new StringBuilder();String x;while((x=r.readLine())!=null)b.append(x);return b.toString();}
 private void snapshot(){new Thread(()->{try{JSONObject j=new JSONObject(read(open("/api/snapshot")));ui.post(()->render(j));}catch(Exception e){ui.post(()->status.setText("OFFLINE • "+e.getClass().getSimpleName()));}}).start();}
 private void render(JSONObject j){JSONObject in=j.optJSONObject("integration"),c=j.optJSONObject("counts"),h=j.optJSONObject("health");JSONArray w=j.optJSONArray("workers");int active=c==null?0:c.optInt("active_workers"),working=c==null?0:c.optInt("working");graph.push(working);status.setText("LIVE • "+(in==null?"unknown":in.optString("short"))+" • SSE");metrics.setText("Active "+active+"   Working "+working+"   Workers "+(w==null?0:w.length()));StringBuilder b=new StringBuilder();JSONObject a=j.optJSONObject("tasks");if(a!=null){add(b,"ACTIVE",a.optJSONArray("active"));add(b,"READY",a.optJSONArray("ready"));add(b,"BLOCKED",a.optJSONArray("blocked"));}tasks.setText(b.length()==0?"No task telemetry":b.toString());String branch=in==null?"?":in.optString("branch","?");tree.setText("NEXUS CORE\n├─ Integration  "+branch+"\n├─ Brain / task authority\n├─ Swarm  "+active+" active\n├─ Workers  "+(w==null?0:w.length())+" observed\n└─ Health  "+(h==null?"telemetry pending":"connected"));}
 private void add(StringBuilder b,String n,JSONArray a){if(a==null)return;b.append(n).append('\n');for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null){String title=x.optString("title");b.append("• ").append(x.optString("task")).append("  ").append(x.optString("progress",x.optString("status")));if(!title.isEmpty())b.append("\n  ").append(title);b.append('\n');}}}
 private void stream(){new Thread(()->{while(running){try{HttpURLConnection c=open("/api/events");c.setRequestProperty("Accept","text/event-stream");BufferedReader r=new BufferedReader(new InputStreamReader(c.getInputStream()));String x;while(running&&(x=r.readLine())!=null)if(x.startsWith("data:")){String d=x.substring(5).trim();try{JSONObject j=new JSONObject(d);ui.post(()->render(j));}catch(Exception ignored){}}}catch(Exception e){try{Thread.sleep(2000);}catch(InterruptedException ignored){}}}}).start();}
 private void tick(){ui.postDelayed(()->{if(running){long s=(System.currentTimeMillis()-connectedAt)/1000;setTitle("Nexus Command Center • "+s+"s live");tick();}},1000);}
 private void configure(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText u=new EditText(this);u.setHint("Authenticated HTTPS endpoint");u.setText(endpoint);EditText t=new EditText(this);t.setHint("Nexus access token");t.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);t.setText(token);box.addView(u);box.addView(t);new AlertDialog.Builder(this).setTitle("Secure connection").setView(box).setPositiveButton("Save",(d,w)->{endpoint=u.getText().toString().replaceAll("/+$","");token=t.getText().toString();getSharedPreferences("nexus",MODE_PRIVATE).edit().putString("endpoint",endpoint).putString("token",token).apply();connectedAt=System.currentTimeMillis();snapshot();}).setNegativeButton("Cancel",null).show();}
 private void googleSignIn(){GetGoogleIdOption google=new GetGoogleIdOption.Builder().setServerClientId("488116567878-0uvf4q2u1h2oh9hbnh45sggbv0q7tidb.apps.googleusercontent.com").setFilterByAuthorizedAccounts(false).setAutoSelectEnabled(false).build();GetCredentialRequest req=new GetCredentialRequest.Builder().addCredentialOption(google).build();CredentialManager.create(this).getCredentialAsync(this,req,null,getMainExecutor(),new CredentialManagerCallback<GetCredentialResponse,GetCredentialException>(){public void onResult(GetCredentialResponse r){try{GoogleIdTokenCredential g=GoogleIdTokenCredential.createFrom(r.getCredential().getData());((Button)findViewById(R.id.signin)).setText("Google • "+g.getDisplayName());events.setText("IDENTITY VERIFIED • Google\n"+events.getText());}catch(Exception e){events.setText("Google identity parse failed\n"+events.getText());}}public void onError(GetCredentialException e){events.setText("Google sign-in: "+e.getClass().getSimpleName()+"\n"+events.getText());}});}
 private void control(String action){if(token.isEmpty()){events.setText("ADMIN LOCKED • configure authenticated Nexus token\n"+events.getText());return;}new Thread(()->{try{HttpURLConnection c=open("/api/control");c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.getOutputStream().write(new JSONObject().put("action",action).toString().getBytes(StandardCharsets.UTF_8));String out=read(c);ui.post(()->events.setText("ADMIN "+action+": "+out+'\n'+events.getText()));}catch(Exception e){ui.post(()->events.setText("ADMIN FAILED: "+e.getClass().getSimpleName()+'\n'+events.getText()));}}).start();}
}
